# Dependencies
markdown:            kramdown

redcarpet:
  extensions: ["tables", "fenced_code_block"]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

exclude:      ["*.Rmd"]


# Setup
title:               Eksploracja danych
tagline:             'kurs dla studentów UKSW'
description:         'Eksploracja danych dla studentów WMP.SNŚ UKSW'
url:                 https://sebkaz.github.io/DataMining
baseurl:             "/DataMining"             
paginate:            5

# About/contact
author:
  name:              Sebastian Zając
  url:               https://sebastianzajac.pl
  email:             szajac2@sgh.waw.pl

# Custom vars
version:             1.0.0
